### Purpose: Using v1 final configuration.
### Added Sigmoid activation function to the final layer of the model.
### Instead of using percentile scores, using raw domain scores again, compare against 20250623_1.
settings:
  device: "cpu"  # or "cpu"
  run_desc: "Seeing the difference adding sigmoid to final layer makes"
  seed: 42
  test_ratio: 0.25
  val_ratio: 0.2 # 0.2 of training data after test split  = 0.75 * 0.2 = 0.15 of total data
data:
  source: "data/encoded/predictor_encoded_20250613.npy"
  destination_base: "outputs/training_runs/"
hyperparams:
  optimizer: "adam"
  loss_function: "mse"
  epochs: 1000
  batch_size: 10000
  n_samples: 100000
  learning_rate: 0.001
  dims: 42 # dimenions of the input data (shape[1], default to 42 for predictor)
schema_version: 1