### Purpose: Test out preprocessing pipeline without filter_datetime functionality.

# the parameters for filtering
filter_params:
  usage_frequency: 0.10
  usage_days: 95
# input data source
source:
  directory: "data/raw/"
  filename: "predictor_data_20250529.csv"
# output data source
target:
  directory: "data/preprocessed/"
  filename: "predictor_preprocessed_20250530.csv"
schema_version: 1