### Purpose: Pull customer information with filter criteria for users created after 2020-04-01 as Jason specified.

# data source
source:
  type: database
  sql_file_path: sql/valid_users_20251117.sql
  sql_params: config/connection/constant_therapy_config.json
# data destination
output:
  dest: data/raw/
  filename: valid_users_20251119.csv
schema_version: 1