### Purpose: Pull raw data according to SQL query for predictor model. SQL query is defined in a separate file and written during v1 development.

# data source
source:
  type: database
  sql_file_path: sql/predictor_data_query_20250529.sql
  sql_params: config/connection/constant_therapy_config.json
# data destination
output:
  dest: data/raw/
  filename: predictor_data_20250529.csv
schema_version: 1