### Purpose: Test encoding pipeline for predictor data, after debugging encoding.py and added target value encoding

source_path: "data/preprocessed/predictor_preprocessed_20250609.csv"
target_path: "data/encoded/predictor_encoded_20250610.npy"
schema_version: 1